CREATE FILE FORMAT IF NOT EXISTS bronze_csv
TYPE= CSV
SKIP_HEADER = 1
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = (' ', 'NULL','null')
EMPTY_FIELD_AS_NULL = TRUE
TRIM_SPACE= TRUE
DATE_FORMAT = 'DD-MM-YYYY';
